---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: '12' # some dependent cookbooks aren't Chef 13 ready

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-6.9
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[certbot::default]
